article_app/urls.py
from django.urls import path
from . import views


app_name = "article_app"


urlpatterns = [
    path("", views.ArticleListView.as_view(), name="article_list"),
    path("<slug:slug>/<int:pk>/", views.ArticleDetailView.as_view(), name="article_detail")
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='root.html'), name="root"),
    path('admin/', admin.site.urls),
    path('article/', include("article_app.urls", namespace="article_app")),
    path('contact/', include("contact_app.urls", namespace="contact_app")),
]

contact_app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = "contact_app"


urlpatterns = [
    path("form/", views.ContactRequestFormView.as_view(), name="contact_form"),
    path("success/", TemplateView.as_view(template_name="contact_app/success_form.html"), name="success_form")
]

article_app/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext as _
from django.template.defaultfilters import slugify
from django.shortcuts import reverse
from django.utils import timezone


class Article(models.Model):
    """
        Article Model Fields:
        title => str article title
        slug => str slug not required by user, dynamically filled with title
        content => str for Article Text Content
        author => fk to custom made user in custom_user_app & registered in settings
        publication_datetime => date & time of Article publication
        is_online => True or False to mark the Article as published or not
        created_at => auto created field for time the article save in db
    """
    title = models.CharField(
        max_length=200, blank=False, null=False,
        verbose_name=_("Article Title")
    )

    slug = models.SlugField(
        max_length=255, blank=True, null=True,
        verbose_name=_("Slug")
    )

    content = models.TextField(
        blank=False, null=False, verbose_name=_("Article Content")
    )

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="articles",
        on_delete=models.CASCADE, blank=False, null=False,
        verbose_name=_("Article Author")
    )

    publication_datetime = models.DateTimeField(
        default=timezone.now, verbose_name=_("Publish Date and Time")
    )

    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name=_("Created at")
    )

    is_online = models.BooleanField(
        default=False, verbose_name=_("Make it Online")
    )

    class Meta:
        """
            ordering objects in Descending Order
            assign transitionable verbose name / plural
        """
        ordering = ("-publication_datetime",)
        verbose_name = _("Article")
        verbose_name_plural = _("Articles")

    def get_absolute_url(self):
        # build url dynamically with slug & id
        return reverse("article_app:article_detail", args=[self.slug, self.pk])

    def save(self, *args, **kwargs):
        # slugify the title for slug field on save
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        # represent Article by its title
        return self.title

contact_app/models.py
from django.db import models
from django.utils.translation import gettext as _


class ContactRequest(models.Model):
    """
        Contact Request Fields:
        email => sender email
        name => sender name
        date => sending date
    """

    email = models.EmailField(
        max_length=254, blank=False, null=False,
        verbose_name=_("Email")
    )

    name = models.CharField(
        max_length=255, blank=False, null=False,
        verbose_name=_("Name")
    )

    content = models.TextField(
        blank=False, null=False, verbose_name=_("Content")
    )

    date = models.DateField(
        auto_now_add=True, verbose_name=_("Contact Request Date")
    )

    class Meta:
        """
            ordering objects in Descending Order
            assign transitionable verbose name / plural
        """
        ordering = ("-date",)
        verbose_name = _("Contact Request")
        verbose_name_plural = _("Contact Requests")

    def __str__(self):
        # represent Contact Request by its Sender Name
        return self.name

custom_user_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

contact_app/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings
from .models import ContactRequest


class ContactRequestForm(forms.ModelForm):
    class Meta:
        model = ContactRequest
        exclude = ("date",)  # exclude it since it already auto generated.

    def send_email(self, subject, content):
        send_mail(
            subject,
            content,
            settings.EMAIL_HOST_USER,
            ['dev.omaribrahim@gmail.com', 'debug@mir.de'],
            fail_silently=False,
        )

article_app/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import Article


class ArticleListView(ListView):
    context_object_name = "articles"
    paginate_by = 5
    template_name = "article_app/article_list.html"

    def get_queryset(self):
        """ only make published articles display """
        return Article.objects.filter(is_online=True)


class ArticleDetailView(DetailView):
    # if the article is not published will not be accessed
    queryset = Article.objects.filter(is_online=True)
    context_object_name = "article"
    query_pk_and_slug = True
    template_name = "article_app/article_detail.html"

contact_app/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.shortcuts import reverse
from django.urls import reverse_lazy
from .forms import ContactRequestForm


class ContactRequestFormView(FormView):
    template_name = "contact_app/contact_form.html"
    form_class = ContactRequestForm
    success_url = reverse_lazy("contact_app:success_form")

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        content_request = form.save()
        form.send_email(
            subject=content_request.name,
            content=content_request.content,
        )
        return super().form_valid(form)

custom_user_app/views.py
from django.shortcuts import render

# Create your views here.

templates/article_app/article_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ article.title }}</title>
</head>
<body>
    <h1>{{ article.title }}</h1>
    <p>content: {{ article.content }}</p>
    <span>author name: {{ article.author.get_full_name }}</span> <br>
    <span>created date: {{ article.publication_datetime }}</span>
    <p><a href="{% url 'article_app:article_list' %}">see article list</a> </p>
</body>
</html>

templates/article_app/article_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article List</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <style>
        #pagination_container {
            position: fixed;
            bottom: 15px;
            left: 20px;
        }
        h1 {
            margin-left: 30px;
        }
    </style>
</head>
<body>
    {% for article in articles %}
        <h1><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h1>
        <hr>
    {% empty %}
        <h1>No Articles yet</h1>
    {% endfor %}

    <nav aria-label="Page navigation example" id="pagination_container">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">&laquo;</a>
                </li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item"><a class="page-link active">{{ i }}</a></li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">&raquo;</a>
                </li>
            {% endif %}
        </ul>
    </nav>

</body>
</html>

templates/contact_app/contact_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact Form</title>
</head>
<body>

    <form method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>

</body>
</html>

templates/contact_app/success_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Success</title>
</head>
<body>
    <h1>Form submitted Successfully</h1>
</body>
</html>

templates/not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
</body>
</html>

templates/root.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1><a href="{% url 'article_app:article_list' %}">Articles</a></h1>
    <h1><a href="{% url 'contact_app:contact_form' %}">Contact</a></h1>
</body>
</html>